packages:
  - 'apps/**'
  - 'sync/*'
  - 'configurations/*'
  - 'packages/**'
  - 'examples/**'

catalog:
  '@types/node': ^20.19.27
  date-fns: 4.1.0
  eslint: ^9.39.2
  lucide-react: ^0.556.0
  motion: ^12.24.10
  server-only: ^0.0.1
  superjson: ^2.2.6
  typescript: ^5.9.3
  zod: ^4.3.5
  tsx: ^4.21.0
  tsup: ^8.5.1

catalogs:
  env:
    '@t3-oss/env-nextjs': ^0.13.10
    dotenv: ^17.2.3
  next:
    next: &NEXT_VERSION 16.1.1
    eslint-config-next: *NEXT_VERSION
    next-themes: ^0.4.6
  prisma:
    '@prisma/client': &PRISMA_VERSION ^7.2.0
    '@prisma/adapter-neon': *PRISMA_VERSION
    prisma: *PRISMA_VERSION
  react:
    '@types/react': &REACT_VERSION 19.2.2
    '@types/react-dom': *REACT_VERSION
    react: *REACT_VERSION
    react-dom: *REACT_VERSION
    react-error-boundary: ^6.0.2
  coinbase:
    '@coinbase/cdp-core': &CDP_CORE_VERSION ^0.0.74
    '@coinbase/cdp-hooks': *CDP_CORE_VERSION
    '@coinbase/cdp-solana-standard-wallet': *CDP_CORE_VERSION
    '@coinbase/cdp-wagmi': *CDP_CORE_VERSION
    '@coinbase/cdp-sdk': ^1.40.1
  solana:
    '@solana/kit': &SOLANA_VERSION ^5.0.0
    '@solana/react': *SOLANA_VERSION
    '@solana/transaction-messages': *SOLANA_VERSION
    '@solana/transactions': *SOLANA_VERSION
  trpc:
    '@trpc/client': &TRPC_VERSION ^11.8.1
    '@trpc/react-query': *TRPC_VERSION
    '@trpc/server': *TRPC_VERSION
  x402:
    'x402': &X402_VERSION ^0.7.1
    'x402-fetch': *X402_VERSION
    'x402-next': *X402_VERSION
    'x402-express': *X402_VERSION
    'x402-hono': *X402_VERSION
  tailwind:
    '@tailwindcss/postcss': &TAILWIND_VERSION ^4
    tailwindcss: *TAILWIND_VERSION
  hono:
    '@hono/node-server': ^1.13.8
    hono: ^4.7.1
  express:
    express: ^5.2.1
    '@types/express': ^5.0.1
  clickhouse:
    '@clickhouse/client': ^1.12.1
  react-query:
    '@tanstack/react-query': ^5.90.16
    '@tanstack/react-query-devtools': ^5.91.2
