// oxfmt-ignore
import "@/app/api/x402/merchants/route";
// oxfmt-ignore
import "@/app/api/x402/merchants/[address]/transactions/route";
// oxfmt-ignore
import "@/app/api/x402/merchants/[address]/stats/route";
// oxfmt-ignore
import "@/app/api/x402/wallets/[address]/transactions/route";
// oxfmt-ignore
import "@/app/api/x402/wallets/[address]/stats/route";
// oxfmt-ignore
import "@/app/api/x402/facilitators/route";
// oxfmt-ignore
import "@/app/api/x402/facilitators/stats/route";
// oxfmt-ignore
import "@/app/api/x402/resources/route";
// oxfmt-ignore
import "@/app/api/x402/resources/search/route";
// oxfmt-ignore
import "@/app/api/x402/origins/[id]/resources/route";
// oxfmt-ignore
import "@/app/api/x402/registry/register/route";
// oxfmt-ignore
import "@/app/api/x402/registry/register-origin/route";
// oxfmt-ignore
import "@/app/api/x402/registry/origin/route";
// oxfmt-ignore
import "@/app/api/x402/send/route";
