import { checkEndpointSchema, getWarningsForL3 } from '@agentcash/discovery';
import type {
  AuditWarning,
  EndpointMethodAdvisory,
} from '@agentcash/discovery';
import { PROBE_TIMEOUT_MS } from './utils';

export type ProbeX402Result =
  | {
      success: true;
      advisory: EndpointMethodAdvisory;
      warnings: AuditWarning[];
    }
  | { success: false; error: string };

/**
 * Probes a URL and returns the first advisory that carries x402 payment options.
 * Delegates entirely to checkEndpointSchema — no re-validation.
 *
 * @param preferredMethod - HTTP method from OpenAPI discovery. When provided it is
 *   tried first so that probe results don't override a known-correct method.
 */
export async function probeX402Endpoint(
  url: string,
  preferredMethod?: string,
): Promise<ProbeX402Result> {
  const result = await checkEndpointSchema({
    url,
    probe: true,
    signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
  });

  if (!result.found) {
    const causeMessages = {
      not_found: 'Endpoint did not return a 402 payment challenge',
      network: 'Network error reaching endpoint',
      timeout: 'Endpoint timed out',
    };
    return {
      success: false,
      error: result.message ?? causeMessages[result.cause],
    };
  }

  const candidates = result.advisories.filter(a =>
    a.paymentOptions?.some(p => p.protocol === 'x402')
  );

  // If we have a method from the OpenAPI spec, trust it over the probe's guess.
  // Fall back to POST > GET > PUT > PATCH > DELETE preference; HEAD is excluded
  // as it is auto-generated by OpenAPI for every GET endpoint.
  const METHOD_PREFERENCE = [
    ...(preferredMethod ? [preferredMethod.toUpperCase()] : []),
    'POST',
    'GET',
    'PUT',
    'PATCH',
    'DELETE',
  ];

  const preferred = METHOD_PREFERENCE.flatMap(m =>
    candidates.filter(a => a.method === m)
  )[0] ?? candidates[0];

  if (preferred) {
    return {
      success: true,
      advisory: preferred,
      warnings: getWarningsForL3(preferred),
    };
  }

  return { success: false, error: 'No valid x402 response found' };
}
