import { checkEndpointSchema, getWarningsForL3 } from '@agentcash/discovery';
import type {
  AuditWarning,
  EndpointMethodAdvisory,
} from '@agentcash/discovery';
import { PROBE_TIMEOUT_MS } from './utils';

export type ProbeX402Result =
  | {
      success: true;
      advisory: EndpointMethodAdvisory;
      warnings: AuditWarning[];
    }
  | { success: false; error: string };

/**
 * Probes a URL and returns the first advisory that carries x402 payment options.
 * Delegates entirely to checkEndpointSchema — no re-validation.
 *
 * @param preferredMethod - HTTP method from OpenAPI discovery. When provided it is
 *   tried first so that probe results don't override a known-correct method.
 */
export async function probeX402Endpoint(
  url: string,
  preferredMethod?: string,
): Promise<ProbeX402Result> {
  const result = await checkEndpointSchema({
    url,
    probe: true,
    signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
  });

  if (!result.found) {
    const causeMessages = {
      not_found: 'Endpoint did not return a 402 payment challenge',
      network: 'Network error reaching endpoint',
      timeout: 'Endpoint timed out',
    };
    return {
      success: false,
      error: result.message ?? causeMessages[result.cause],
    };
  }

  const candidates = result.advisories.filter(a =>
    a.paymentOptions?.some(p => p.protocol === 'x402')
  );

  // Prefer POST > GET > PUT > PATCH > DELETE; HEAD is excluded as it is
  // auto-generated by OpenAPI for every GET endpoint.
  const METHOD_PREFERENCE = ['POST', 'GET', 'PUT', 'PATCH', 'DELETE'];

  const preferred = METHOD_PREFERENCE.flatMap(m =>
    candidates.filter(a => a.method === m)
  )[0] ?? candidates[0];

  if (preferred) {
    // If the OpenAPI spec declares a specific method, trust it over the probe.
    // Some APIs (e.g. Nansen) return 402 for all HTTP methods because their
    // payment middleware fires before method routing, so the probe may land on
    // PATCH/PUT even though the endpoint is declared as POST in the spec.
    // In that case we keep the probe's paymentOptions but correct the method.
    const advisory =
      preferredMethod && preferred.method !== preferredMethod.toUpperCase()
        ? { ...preferred, method: preferredMethod.toUpperCase() as EndpointMethodAdvisory['method'] }
        : preferred;

    return {
      success: true,
      advisory,
      warnings: getWarningsForL3(advisory),
    };
  }

  return { success: false, error: 'No valid x402 response found' };
}
