import { router } from '@/lib/router';
import '@/lib/routes-barrel';

import { enrichOpenApiDocument } from '@/lib/agent/openapi';
import { jsonValueSchema } from '@/lib/json';

/**
 * OpenAPI 3.1 document for the public API. The base document is generated by
 * `@agentcash/router` from the route definitions (paths, query/body/output
 * schemas, payment info); `enrichOpenApiDocument` layers on the typed error
 * model, rate-limit headers, path parameters, operation descriptions and the
 * versioning policy. See `src/lib/agent/openapi.ts`.
 */
const generate = router.openapi();

let cached: string | null = null;

export async function GET(request: Request) {
  if (!cached) {
    const base = jsonValueSchema.parse(await (await generate(request)).json());
    cached = JSON.stringify(enrichOpenApiDocument(base), null, 2);
  }
  return new Response(cached, {
    headers: {
      'Content-Type': 'application/vnd.oai.openapi+json; charset=utf-8',
      'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
      'Access-Control-Allow-Origin': '*',
      Vary: 'Accept',
    },
  });
}
