import { Metrics } from './types';

function toNumber(value: number | string | null | undefined): number | undefined {
  if (value === null || value === undefined) {
    return undefined;
  }
  const num = typeof value === 'string' ? Number(value) : value;
  return isNaN(num) ? undefined : num;
}

export function mapMetric(metric: Metrics) {
  return {
        totalCount1h: toNumber(metric.total_count_1h),
        totalCount6h: toNumber(metric.total_count_6h),
        totalCount24h: toNumber(metric.total_count_24h),
        totalCount3d: toNumber(metric.total_count_3d),
        totalCount7d: toNumber(metric.total_count_7d),
        totalCount15d: toNumber(metric.total_count_15d),
        totalCount30d: toNumber(metric.total_count_30d),
        totalCountAllTime: toNumber(metric.total_count_all_time),
        uptime1hPct: toNumber(metric.uptime_1h_pct),
        uptime6hPct: toNumber(metric.uptime_6h_pct),
        uptime24hPct: toNumber(metric.uptime_24h_pct),
        uptime3dPct: toNumber(metric.uptime_3d_pct),
        uptime7dPct: toNumber(metric.uptime_7d_pct),
        uptime15dPct: toNumber(metric.uptime_15d_pct),
        uptime30dPct: toNumber(metric.uptime_30d_pct),
        uptimeAllTimePct: toNumber(metric.uptime_all_time_pct),
        p50_1hMs: toNumber(metric.p50_1h_ms),
        p50_6hMs: toNumber(metric.p50_6h_ms),
        p50_24hMs: toNumber(metric.p50_24h_ms),
        p50_3dMs: toNumber(metric.p50_3d_ms),
        p50_7dMs: toNumber(metric.p50_7d_ms),
        p50_15dMs: toNumber(metric.p50_15d_ms),
        p50_30dMs: toNumber(metric.p50_30d_ms),
        p50AllMs: toNumber(metric.p50_all_time_ms),
        p90_1hMs: toNumber(metric.p90_1h_ms),
        p90_6hMs: toNumber(metric.p90_6h_ms),
        p90_24hMs: toNumber(metric.p90_24h_ms),
        p90_3dMs: toNumber(metric.p90_3d_ms),
        p90_7dMs: toNumber(metric.p90_7d_ms),
        p90_15dMs: toNumber(metric.p90_15d_ms),
        p90_30dMs: toNumber(metric.p90_30d_ms),
        p90AllMs: toNumber(metric.p90_all_time_ms),
        p99_1hMs: toNumber(metric.p99_1h_ms),
        p99_6hMs: toNumber(metric.p99_6h_ms),
        p99_24hMs: toNumber(metric.p99_24h_ms),
        p99_3dMs: toNumber(metric.p99_3d_ms),
        p99_7dMs: toNumber(metric.p99_7d_ms),
        p99_15dMs: toNumber(metric.p99_15d_ms),
        p99_30dMs: toNumber(metric.p99_30d_ms),
        p99AllMs: toNumber(metric.p99_all_time_ms),
        count_2xx_1h: toNumber(metric.count_2xx_1h),
        count_2xx_6h: toNumber(metric.count_2xx_6h),
        count_2xx_24h: toNumber(metric.count_2xx_24h),
        count_2xx_3d: toNumber(metric.count_2xx_3d),
        count_2xx_7d: toNumber(metric.count_2xx_7d),
        count_2xx_15d: toNumber(metric.count_2xx_15d),
        count_2xx_30d: toNumber(metric.count_2xx_30d),
        count_2xx_all_time: toNumber(metric.count_2xx_all_time),
        count_3xx_1h: toNumber(metric.count_3xx_1h),
        count_3xx_6h: toNumber(metric.count_3xx_6h),
        count_3xx_24h: toNumber(metric.count_3xx_24h),
        count_3xx_3d: toNumber(metric.count_3xx_3d),
        count_3xx_7d: toNumber(metric.count_3xx_7d),
        count_3xx_15d: toNumber(metric.count_3xx_15d),
        count_3xx_30d: toNumber(metric.count_3xx_30d),
        count_3xx_all_time: toNumber(metric.count_3xx_all_time),
        count_4xx_1h: toNumber(metric.count_4xx_1h),
        count_4xx_6h: toNumber(metric.count_4xx_6h),
        count_4xx_24h: toNumber(metric.count_4xx_24h),
        count_4xx_3d: toNumber(metric.count_4xx_3d),
        count_4xx_7d: toNumber(metric.count_4xx_7d),
        count_4xx_15d: toNumber(metric.count_4xx_15d),
        count_4xx_30d: toNumber(metric.count_4xx_30d),
        count_4xx_all_time: toNumber(metric.count_4xx_all_time),
        count_5xx_1h: toNumber(metric.count_5xx_1h),
        count_5xx_6h: toNumber(metric.count_5xx_6h),
        count_5xx_24h: toNumber(metric.count_5xx_24h),
        count_5xx_3d: toNumber(metric.count_5xx_3d),
        count_5xx_7d: toNumber(metric.count_5xx_7d),
        count_5xx_15d: toNumber(metric.count_5xx_15d),
        count_5xx_30d: toNumber(metric.count_5xx_30d),
        count_5xx_all_time: toNumber(metric.count_5xx_all_time),
  };
}
