import type { OutputComponent } from "../types";

import z from "zod";
import { api } from "@/trpc/client";
import { Skeleton } from "@/components/ui/skeleton";
import { ToolOutput } from "@/components/ai-elements/tool";
import Image from "next/image";

const freepikOutputSchema = z.object({
  data: z.object({
    task_id: z.string(),
    status: z.string(),
  }),
});

export const FreepikOutput: OutputComponent = ({ output, errorText }) => {
  if (errorText) {
    return (
      <div className="type-supporting-body text-destructive">{errorText}</div>
    );
  }

  const parseResult = freepikOutputSchema.safeParse(output);

  if (!parseResult.success) {
    return (
      <ToolOutput
        output={parseResult.error.issues.map((issue) => ({
          path: issue.path.map(String),
          message: issue.message,
        }))}
      />
    );
  }

  const { task_id } = parseResult.data.data;

  return <FreepikImageDisplay task_id={task_id} />;
};

const FreepikImageDisplay: React.FC<{ task_id: string }> = ({ task_id }) => {
  const {
    data: task,
    isLoading: isTaskLoading,
    error: taskError,
  } = api.user.tools.freepik.getTask.useQuery(
    { task_id },
    {
      refetchInterval: (query) =>
        query.state.data?.data.status === "COMPLETED" ? false : 2000,
    }
  );

  if (taskError) {
    return (
      <div className="type-supporting-body text-destructive">
        {taskError.message}
      </div>
    );
  }

  if (isTaskLoading || task?.data.status === "IN_PROGRESS") {
    return <Skeleton className="size-48" />;
  }

  return (
    <div className="max-h-48">
      {task?.data.generated.map((image) => (
        <Image
          key={image}
          src={image}
          alt="Generated by Freepik"
          width={512}
          height={512}
          unoptimized
          className="max-h-48 w-auto rounded-md"
        />
      ))}
    </div>
  );
};
