import type { EcosystemItem } from './schema';

export const ecosystemItems: EcosystemItem[] = [
  {
    name: '1Shot API',
    description:
      'A general purpose fascilitator to monetize any n8n workflow with your favorite ERC-20 token.',
    logoUrl: 'https://www.x402.org/logos/1shot-api.png',
    websiteUrl:
      'https://docs.1shotapi.com/automation/n8n.html#monetize-n8n-workflows-with-x402',
    category: 'Infrastructure & Tooling',
  },
  {
    name: '402104',
    description:
      'Generate expirable, paywalled links to private ANS-104 DataItems on Arweave. Compatible with both S3 and ANS-104 data standards.',
    logoUrl: 'https://www.x402.org/logos/402104.png',
    websiteUrl: 'https://402.load.network',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'AEON',
    description:
      'The omnichain settlement layer that enables AI agents to seamlessly pay millions of real-world merchants across SEA, LATAM, and Africa — powered by x402 and USDC.',
    logoUrl: 'https://www.x402.org/logos/aeon.png',
    websiteUrl: 'https://aeon.xyz/AIPayment',
    category: 'Services/Endpoints',
  },
  {
    name: 'AurraCloud',
    description:
      'AI agents hosting and Tooling Platform, with MCP, smartWallets, OpenAI API compatibility and X402 support.',
    logoUrl: 'https://www.x402.org/logos/aurracloud.png',
    websiteUrl: 'https://aurracloud.com/x402',
    category: 'Services/Endpoints',
  },
  {
    name: 'Axios & Fetch Clients',
    description:
      'Reference TypeScript clients for x402 using both Axios and Fetch. Easily integrate x402 payments into your own applications.',
    logoUrl: 'https://www.x402.org/logos/axios-fetch-clients.png',
    websiteUrl:
      'https://github.com/coinbase/x402/tree/main/examples/typescript/clients',
    category: 'Client-Side Integrations',
  },
  {
    name: 'Bonsai',
    description:
      'Create, remix, and trade evolving media. Use our API to generate AI content using smart media protocol (SMP) templates.',
    logoUrl: 'https://www.x402.org/logos/bonsai.png',
    websiteUrl:
      'https://onbonsai.gitbook.io/docs/smart-media/content-generation-api',
    category: 'Services/Endpoints',
  },
  {
    name: 'CDP Facilitator',
    description:
      'Best-in-class x402 facilitator. Fee-free USDC settlement on Base Mainnet. KYT/OFAC checks on every transaction.',
    logoUrl: 'https://www.x402.org/logos/cdp.png',
    websiteUrl: 'https://docs.cdp.coinbase.com/x402/docs/quickstart-sellers',
    category: 'Facilitators',
  },
  {
    name: 'Corbits',
    description:
      'A production grade facilitator which supports multi-network, multi-token, multi-payment schemes.',
    logoUrl: 'https://www.x402.org/logos/corbits.png',
    websiteUrl: 'https://corbits.dev',
    category: 'Facilitators',
  },
  {
    name: 'Daydreams Router',
    description:
      'Daydreams router provides x402 enabled LLM inference for agents and applications. All major providers are supported. Build the future of nanoservices.',
    logoUrl: 'https://www.x402.org/logos/router-logo.png',
    websiteUrl: 'https://router.daydreams.systems',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Faremeter',
    description:
      'A lightweight OSS x402 framework powered by client-, middleware-, and server-side plugins ensuring maximum composability and extensibility.',
    logoUrl: 'https://www.x402.org/logos/faremeter.png',
    websiteUrl: 'https://faremeter.xyz',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Firecrawl',
    description:
      'Firecrawl is a web scraping API that allows you to turn websites into LLM-ready data.',
    logoUrl: 'https://www.x402.org/logos/firecrawl.png',
    websiteUrl: 'https://firecrawl.dev',
    category: 'Services/Endpoints',
  },
  {
    name: 'Fluora',
    description:
      'Fluora is a MonetizedMCP marketplace, enabling AI agents to autonomously find and purchase services. Payments are powered by x402',
    logoUrl: 'https://www.x402.org/logos/fluora.png',
    websiteUrl: 'https://www.fluora.ai/',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Gloria AI',
    description:
      'Gloria is an AI-powered provider of real-time, high-signal, customizable news data to AI agents and agent systems that need structured signals for any use case.',
    logoUrl: 'https://www.x402.org/logos/gloria.png',
    websiteUrl: 'https://itsgloria.ai',
    category: 'Services/Endpoints',
  },
  {
    name: 'Grove API',
    description:
      'A unified API you can /fund using x402 to /tip anyone on the internet.',
    logoUrl: 'https://www.x402.org/logos/grove-api-logo.png',
    websiteUrl: 'https://grove.city/api',
    category: 'Services/Endpoints',
  },
  {
    name: 'Heurist Deep Research',
    description:
      'The first Web3 native AI research platformpowered by x402. Users can pay per-query with USDC to get comprehensive multi-page research reports generated by AI agents, with no API keys or subscriptions required.',
    logoUrl: 'https://www.x402.org/logos/heurist-deep-research-icon.png',
    websiteUrl: 'https://research.heurist.ai',
    category: 'Services/Endpoints',
  },
  {
    name: 'Heurist Mesh',
    description:
      'Heurist Mesh provides a library of composable crypto skills for any AI agent. Equip your AI with expert crypto analysis abilities, from tracking whale wallets to spotting trending new tokens to analyzing onchain markets with full support for MCP and the X402 payment standard.',
    logoUrl: 'https://www.x402.org/logos/heurist-mesh.png',
    websiteUrl: 'https://mesh.heurist.ai/',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Latinum Agentic Commerce',
    description:
      'An open-source MCP wallet and facilitator that agents can use to pay 402 payment requests.',
    logoUrl: 'https://www.x402.org/logos/latinum.png',
    websiteUrl: 'https://latinum.ai',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'MCP Server Example',
    description:
      'A reference implementation MCP server and wallet to call x402 endpoints. Explore the code and run your own server.',
    logoUrl: 'https://www.x402.org/logos/mcp-example.png',
    websiteUrl:
      'https://github.com/coinbase/x402/tree/main/examples/typescript/mcp',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'MCPay',
    description: 'Build and monetize MCP servers.',
    logoUrl: 'https://www.x402.org/logos/mcpay-logo.png',
    websiteUrl: 'https://mcpay.tech',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Meridian',
    description: 'Multi-chain facilitator with developer-first features.',
    logoUrl: 'https://www.x402.org/logos/meridian-logo.png',
    websiteUrl: 'https://mrdn.finance',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Mogami examples',
    description: 'A collection of x402 examples in Java (client and server)',
    logoUrl: 'https://www.x402.org/logos/logo_mogami_vertical_small.png',
    websiteUrl: 'https://mogami.tech/#examples',
    category: 'Learning & Community Resources',
  },
  {
    name: 'Mogami facilitator',
    description:
      'Facilitator running on base (testnet & mainnet) with a development console - You can run it as a Docker image within your own infrastructure, or use our always-on hosted facilitator online',
    logoUrl: 'https://www.x402.org/logos/logo_mogami_vertical_small.png',
    websiteUrl: 'https://facilitator.mogami.tech',
    category: 'Facilitators',
  },
  {
    name: 'Mogami java client SDK',
    description:
      'The Mogami Java Client SDK makes it easy to bring x402 payments into your Java application',
    logoUrl: 'https://www.x402.org/logos/logo_mogami_vertical_small.png',
    websiteUrl: 'https://mogami.tech/#clientSDK',
    category: 'Client-Side Integrations',
  },
  {
    name: 'Mogami java server SDH (Spring boot)',
    description:
      'The Mogami Java Server SDK lets you turn any endpoint of your spring application into a pay-per-call API using the x402 protocol',
    logoUrl: 'https://www.x402.org/logos/logo_mogami_vertical_small.png',
    websiteUrl: 'https://mogami.tech/#serverSDK',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Neynar',
    description:
      'Powering social data on Farcaster for agents and humans. Get cast info and more.',
    logoUrl: 'https://www.x402.org/logos/neynar.png',
    websiteUrl:
      'https://neynar.com/blog/agents-frames-and-the-future-of-farcaster-neynar-s-vision-for-x402',
    category: 'Services/Endpoints',
  },
  {
    name: 'Node Servers (Hono, Express, Advanced)',
    description:
      'Reference x402 server implementations in Node.js using Hono and Express, plus an advanced example with dynamic pricing and complex logic.',
    logoUrl: 'https://www.x402.org/logos/node-servers.png',
    websiteUrl:
      'https://github.com/coinbase/x402/tree/main/examples/typescript/servers',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Onchain',
    description:
      "Onchain is x402's Intelligent Intermediary Layer for Aggregating Facilitators.",
    logoUrl: 'https://www.x402.org/logos/onchain.png',
    websiteUrl: 'https://onchain.fi',
    category: 'Services/Endpoints',
  },
  {
    name: 'PayAI Facilitator',
    description:
      'Accept x402 payments on all networks including Avalanche, Base, Polygon, Sei, Solana, and more! Get started in less than 1 minute. Supports all tokens. No API Keys required.',
    logoUrl: 'https://www.x402.org/logos/payai.svg',
    websiteUrl: 'https://facilitator.payai.network',
    category: 'Facilitators',
  },
  {
    name: 'Pinata',
    description:
      'Account-free IPFS uploads and retrievals using crypto payments, powered by x402. Pay for private or public IPFS storage and retrieval without an account or API key.',
    logoUrl: 'https://www.x402.org/logos/pinata.png',
    websiteUrl: 'https://402.pinata.cloud/',
    category: 'Services/Endpoints',
  },
  {
    name: 'Proxy402',
    description:
      'Turn your URLs into paid content. Set a price, share your link, and collect payments instantly. By Fewsats.',
    logoUrl: 'https://www.x402.org/logos/proxy402.png',
    websiteUrl: 'https://proxy402.com/',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Questflow',
    description:
      'The orchestration layer for the multi-agent economy. Orchestrate multiple AI agents to research, take action and earn rewards on-chain, autonomously.',
    logoUrl: 'https://www.x402.org/logos/questflow.png',
    websiteUrl:
      'https://questflow.ai?utm_source=x402_website&utm_medium=ecosystem',
    category: 'Services/Endpoints',
  },
  {
    name: 'Snack Money API',
    description:
      'Micropayment platform for X, Farcaster, baseapp and verifiable identities.',
    logoUrl: 'https://www.x402.org/logos/snackmoney.png',
    websiteUrl: 'https://api.snack.money/docs',
    category: 'Services/Endpoints',
  },
  {
    name: 'thirdweb',
    description:
      'Client side TypeScript SDK and HTTP API to pay for any x402 compatible endpoint from your apps or agents.',
    logoUrl: 'https://www.x402.org/logos/thirdweb-logo.png',
    websiteUrl: 'https://portal.thirdweb.com/payments/x402/client',
    category: 'Client-Side Integrations',
  },
  {
    name: 'thirdweb',
    description:
      'Server side TypeScript SDK and facilitator HTTP API supporting 170+ chains and 4000+ tokens.',
    logoUrl: 'https://www.x402.org/logos/thirdweb-logo.png',
    websiteUrl: 'https://portal.thirdweb.com/payments/x402/facilitator',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'tip.md',
    description:
      'A crypto tipping service that enables AI assistants to help users send cryptocurrency tips to content creators directly from their chat interface. USDC tips via MCP are powered by x402. The MCP service allows for checking wallet types and preparing cryptocurrency tips for users/agents to complete.',
    logoUrl: 'https://www.x402.org/logos/tipdotmd.png',
    websiteUrl: 'https://www.tip.md/documentation?tab=mcp-server',
    category: 'Services/Endpoints',
  },
  {
    name: 'Tweazy',
    description:
      'The best way to read tweets onchain / Powered by x402, MCP & CDP Smart Wallets',
    logoUrl: 'https://www.x402.org/logos/tweazy.png',
    websiteUrl: 'https://github.com/aaronjmars/tweazy',
    category: 'Client-Side Integrations',
  },
  {
    name: 'x402 Example Gallery',
    description:
      'A collection of x402 examples including Next.js integration, Go Proxy, agent use-cases, authentication flows, and more. Explore practical code samples to accelerate your x402 journey.',
    logoUrl: 'https://www.x402.org/logos/x402-examples.png',
    websiteUrl:
      'https://github.com/coinbase/x402/tree/main/examples/typescript',
    category: 'Learning & Community Resources',
  },
  {
    name: 'x402.org Facilitator',
    description: 'Default testnet facilitator for x402',
    logoUrl: 'https://www.x402.org/logos/x402-logo.png',
    websiteUrl: 'https://x402.org',
    category: 'Facilitators',
  },
  {
    name: 'x402.rs Facilitator',
    description:
      'Independent, open-source facilitator in Rust. Easy to self-host, extend to new networks, or use via our hosted instance.',
    logoUrl: 'https://www.x402.org/logos/x402-rs.svg',
    websiteUrl: 'https://facilitator.x402.rs',
    category: 'Facilitators',
  },
  {
    name: 'x402scan',
    description: 'An ecosystem explorer for x402 resources and analytics',
    logoUrl: 'https://www.x402.org/logos/x402scan.png',
    websiteUrl: 'https://x402scan.com',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'x402station',
    description:
      'Leading x402 analytics platform with advanced UI for monitoring x402 services. Track real-time performance metrics, x402 API analytics, and service reliability with our comprehensive x402 UI dashboard.',
    logoUrl: 'https://www.x402.org/logos/x402station-logo.png',
    websiteUrl: 'https://x402station.com/',
    category: 'Infrastructure & Tooling',
  },
  {
    name: 'Zyte API',
    description:
      'Zyte API is a unified Web Scraping API for unblocking, browser rendering and extraction.',
    logoUrl: 'https://www.x402.org/logos/zyte-api-x402.png',
    websiteUrl:
      'https://python-zyte-api.readthedocs.io/en/stable/use/x402.html',
    category: 'Services/Endpoints',
  },
] as const;
