import { z } from 'zod';

import { API_ENDPOINTS } from '@/lib/agent/api-endpoints';
import { RATE_LIMIT } from '@/lib/agent/rate-limit-policy';
import { jsonValueSchema } from '@/lib/json';
import {
  API_VERSION,
  API_VERSION_HEADER,
  ORG,
  REPO_URL,
  SITE_URL,
} from '@/lib/site';

import type { JsonValue } from '@/lib/json';

/**
 * Enriches the OpenAPI document generated by `@agentcash/router` with the
 * parts the router can't express on its own:
 *
 *   - a typed error model (`components.schemas.Error`) referenced by every
 *     4xx/5xx response, so agents can handle failures without guessing;
 *   - `RateLimit` / `Retry-After` response headers on every operation;
 *   - path parameters for templated paths (`{address}`, `{id}`);
 *   - a `description` per operation (the router only sets `summary`);
 *   - the versioning / deprecation policy (`x-versioning`, `info.version`,
 *     `X-API-Version` header) and external docs links.
 *
 * The generated document is parsed once at the boundary with a loose schema
 * that names only the members we touch; everything else passes through
 * untouched so a router upgrade can't break spec generation.
 */

// ── Boundary schema for the generated document ───────

const headerObjectSchema = z.looseObject({
  description: z.string().optional(),
  schema: jsonValueSchema.optional(),
});

const parameterObjectSchema = z.looseObject({
  name: z.string(),
  in: z.string(),
});

const responseObjectSchema = z.looseObject({
  description: z.string().optional(),
  headers: z.record(z.string(), headerObjectSchema).optional(),
  content: jsonValueSchema.optional(),
});

const operationObjectSchema = z.looseObject({
  operationId: z.string().optional(),
  summary: z.string().optional(),
  description: z.string().optional(),
  parameters: z.array(parameterObjectSchema).optional(),
  responses: z.record(z.string(), responseObjectSchema).optional(),
});

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

const pathItemObjectSchema = z.looseObject({
  get: operationObjectSchema.optional(),
  post: operationObjectSchema.optional(),
  put: operationObjectSchema.optional(),
  patch: operationObjectSchema.optional(),
  delete: operationObjectSchema.optional(),
});

const openApiDocumentSchema = z.looseObject({
  openapi: z.string(),
  info: z.looseObject({
    title: z.string().optional(),
    version: z.string().optional(),
  }),
  components: z
    .looseObject({
      schemas: z.record(z.string(), jsonValueSchema).optional(),
    })
    .optional(),
  paths: z.record(z.string(), pathItemObjectSchema).optional(),
});

export type OpenApiDocument = z.infer<typeof openApiDocumentSchema>;
type OperationObject = z.infer<typeof operationObjectSchema>;
type ResponseObject = z.infer<typeof responseObjectSchema>;
type HeaderObject = z.infer<typeof headerObjectSchema>;

// ── Static fragments ─────────────────────────────────

export const ERROR_TYPES = [
  'validation_error',
  'invalid_address',
  'not_found',
  'no_discovery',
  'method_not_allowed',
  'not_in_spec',
  'no_valid_resources',
  'registration_failed',
  'rate_limited',
  'internal_error',
  'tunnel',
  'no402',
  'parseErrors',
] as const;

const ERROR_SCHEMA = {
  type: 'object',
  description:
    'Structured error envelope returned for every non-2xx, non-402 response. `error` is an object with a machine-readable `type` for application errors, or a plain string for framework validation failures.',
  required: ['success', 'error'],
  properties: {
    success: { type: 'boolean', const: false },
    error: {
      oneOf: [
        {
          type: 'object',
          required: ['type', 'message'],
          properties: {
            type: {
              type: 'string',
              description: 'Machine-readable error code',
              enum: [...ERROR_TYPES],
            },
            message: {
              type: 'string',
              description: 'Human-readable explanation',
            },
            hint: {
              type: 'string',
              description: 'What the caller can do to resolve the problem',
            },
            details: {
              description: 'Validation issues or other structured context',
            },
            links: {
              type: 'object',
              additionalProperties: { type: 'string', format: 'uri' },
              description: 'Related documentation URLs',
            },
          },
          additionalProperties: true,
        },
        {
          type: 'string',
          description: 'Validation failure message (framework-level)',
        },
      ],
    },
  },
  additionalProperties: true,
} as const satisfies JsonValue;

const errorSchemaJson: JsonValue = structuredClone(ERROR_SCHEMA);

const errorContent = {
  'application/json': { schema: { $ref: '#/components/schemas/Error' } },
} satisfies JsonValue;

const RATE_LIMIT_HEADERS = {
  'RateLimit-Policy': {
    description: `Rate-limit policy (draft-ietf-httpapi-ratelimit-headers), e.g. "${RATE_LIMIT.policyName}";q=${RATE_LIMIT.limit};w=${RATE_LIMIT.windowSeconds}`,
    schema: { type: 'string' },
  },
  RateLimit: {
    description:
      'Current quota: r=remaining requests, t=seconds until the window resets',
    schema: { type: 'string' },
  },
  'X-RateLimit-Limit': { schema: { type: 'integer' } },
  'X-RateLimit-Remaining': { schema: { type: 'integer' } },
  'X-RateLimit-Reset': {
    description: 'Seconds until the window resets',
    schema: { type: 'integer' },
  },
  [API_VERSION_HEADER]: {
    description: 'API version that produced this response',
    schema: { type: 'string', enum: [API_VERSION] },
  },
} satisfies Record<string, HeaderObject>;

const STANDARD_ERROR_RESPONSES = {
  '400': {
    description:
      'Malformed request: invalid address, query parameter, or body. `error.type` is `validation_error` or `invalid_address`.',
    content: errorContent,
  },
  '404': {
    description:
      'Not found: unknown route, or (registry endpoints) no discovery document on the target origin (`no_discovery`).',
    content: errorContent,
  },
  '429': {
    description: `Rate limited: more than ${RATE_LIMIT.limit} requests in ${RATE_LIMIT.windowSeconds}s from one client. Wait \`Retry-After\` seconds.`,
    headers: {
      'Retry-After': {
        description: 'Seconds to wait before retrying',
        schema: { type: 'integer' },
      },
    },
    content: errorContent,
  },
  '500': {
    description:
      'Unexpected server error (`internal_error`). Safe to retry with backoff.',
    content: errorContent,
  },
} satisfies Record<string, ResponseObject>;

const REGISTRY_422 = {
  description:
    'The request was understood but cannot be fulfilled: the endpoint is not in the origin spec (`not_in_spec`), no valid paid resources were found (`no_valid_resources`), or probing the endpoint failed (`tunnel`, `no402`, `parseErrors`).',
  content: errorContent,
} satisfies ResponseObject;

const PAYMENT_REQUIRED_HEADERS = {
  'PAYMENT-REQUIRED': {
    description: 'Base64-encoded x402 payment requirements',
    schema: { type: 'string' },
  },
} satisfies Record<string, HeaderObject>;

const endpointsByOperationId = new Map(
  API_ENDPOINTS.map(endpoint => [endpoint.operationId, endpoint])
);

// ── Enrichment ───────────────────────────────────────

function enrichOperation(
  operation: OperationObject,
  path: string
): OperationObject {
  const operationId = operation.operationId ?? '';
  const catalog = endpointsByOperationId.get(operationId);

  // Path parameters for templated paths.
  const templated = [...path.matchAll(/\{([^}]+)\}/g)].map(m => m[1]!);
  const existingParams = operation.parameters ?? [];
  const declared = new Set(
    existingParams.filter(p => p.in === 'path').map(p => p.name)
  );
  const addedParams = templated
    .filter(name => !declared.has(name))
    .map(name => ({
      name,
      in: 'path',
      required: true,
      description:
        catalog?.pathParams?.find(p => p.name === name)?.description ??
        `${name} path segment`,
      schema: { type: 'string' },
    }));

  // Responses: typed errors + rate-limit headers everywhere.
  const responses = { ...operation.responses };
  for (const [status, body] of Object.entries(STANDARD_ERROR_RESPONSES)) {
    responses[status] ??= structuredClone(body);
  }
  if (operationId.startsWith('x402_registry_register')) {
    responses['422'] ??= structuredClone(REGISTRY_422);
  }
  const r402 = responses['402'];
  if (r402) {
    responses['402'] = {
      ...r402,
      description: r402.description
        ? `${r402.description}. The PAYMENT-REQUIRED header (base64 JSON) and body describe the accepted payment; sign it and retry with an X-Payment header.`
        : 'Payment Required',
      headers: r402.headers ?? structuredClone(PAYMENT_REQUIRED_HEADERS),
    };
  }
  for (const [status, response] of Object.entries(responses)) {
    responses[status] = {
      ...response,
      headers: {
        ...structuredClone(RATE_LIMIT_HEADERS),
        ...response.headers,
      },
    };
  }

  return {
    ...operation,
    description: operation.description ?? catalog?.description,
    ...(templated.length > 0 && {
      parameters: [...existingParams, ...addedParams],
    }),
    responses,
  };
}

export function enrichOpenApiDocument(input: JsonValue): OpenApiDocument {
  const doc = openApiDocumentSchema.parse(input);

  const paths = Object.fromEntries(
    Object.entries(doc.paths ?? {}).map(([path, item]) => {
      const enriched = { ...item };
      for (const method of HTTP_METHODS) {
        const operation = item[method];
        if (operation) enriched[method] = enrichOperation(operation, path);
      }
      return [path, enriched];
    })
  );

  return {
    ...doc,
    info: {
      ...doc.info,
      version: doc.info.version ?? '1.0.0',
      termsOfService: `${SITE_URL}/tos`,
      contact: {
        name: ORG.name,
        url: `${SITE_URL}/contact`,
        email: ORG.email,
      },
      license: { name: 'Apache-2.0', identifier: 'Apache-2.0' },
    },
    externalDocs: {
      description: 'x402scan API documentation',
      url: `${SITE_URL}/docs`,
    },
    'x-versioning': {
      scheme: 'url-path',
      current: API_VERSION,
      basePath: '/api/x402',
      responseHeader: API_VERSION_HEADER,
      policy:
        'Within a version only additive changes are made (new endpoints, optional parameters, response fields). Breaking changes ship under a new path prefix (e.g. /api/x402/v2) and the previous version remains available for at least 90 days.',
      deprecation:
        'Deprecated operations are marked `deprecated: true` in this document and respond with `Deprecation: @<unix-timestamp>` (RFC 9745) and `Sunset: <HTTP-date>` (RFC 8594) headers for their remaining lifetime.',
      changelog: `${REPO_URL}/releases`,
      docs: `${SITE_URL}/docs#versioning-and-deprecation`,
    },
    'x-rate-limit': {
      policy: RATE_LIMIT.policyName,
      limit: RATE_LIMIT.limit,
      windowSeconds: RATE_LIMIT.windowSeconds,
      scope: 'client IP',
      headers: ['RateLimit-Policy', 'RateLimit', 'Retry-After'],
      docs: `${SITE_URL}/docs#rate-limits`,
    },
    components: {
      ...doc.components,
      schemas: {
        ...doc.components?.schemas,
        Error: doc.components?.schemas?.Error ?? errorSchemaJson,
      },
    },
    paths,
  };
}
