-- CreateTable
CREATE TABLE "ResourceOriginMetrics" (
    "id" TEXT NOT NULL,
    "originId" TEXT NOT NULL,
    "totalCount1h" INTEGER,
    "totalCount6h" INTEGER,
    "totalCount24h" INTEGER,
    "totalCount3d" INTEGER,
    "totalCount7d" INTEGER,
    "totalCount15d" INTEGER,
    "totalCount30d" INTEGER,
    "totalCountAllTime" INTEGER,
    "uptime1hPct" DOUBLE PRECISION,
    "uptime6hPct" DOUBLE PRECISION,
    "uptime24hPct" DOUBLE PRECISION,
    "uptime3dPct" DOUBLE PRECISION,
    "uptime7dPct" DOUBLE PRECISION,
    "uptime15dPct" DOUBLE PRECISION,
    "uptime30dPct" DOUBLE PRECISION,
    "uptimeAllTimePct" DOUBLE PRECISION,
    "p50_1hMs" INTEGER,
    "p50_6hMs" INTEGER,
    "p50_24hMs" INTEGER,
    "p50_3dMs" INTEGER,
    "p50_7dMs" INTEGER,
    "p50_15dMs" INTEGER,
    "p50_30dMs" INTEGER,
    "p50AllTimeMs" INTEGER,
    "p90_1hMs" INTEGER,
    "p90_6hMs" INTEGER,
    "p90_24hMs" INTEGER,
    "p90_3dMs" INTEGER,
    "p90_7dMs" INTEGER,
    "p90_15dMs" INTEGER,
    "p90_30dMs" INTEGER,
    "p90AllTimeMs" INTEGER,
    "p99_1hMs" INTEGER,
    "p99_6hMs" INTEGER,
    "p99_24hMs" INTEGER,
    "p99_3dMs" INTEGER,
    "p99_7dMs" INTEGER,
    "p99_15dMs" INTEGER,
    "p99_30dMs" INTEGER,
    "p99AllTimeMs" INTEGER,
    "count_2xx_1h" INTEGER,
    "count_2xx_6h" INTEGER,
    "count_2xx_24h" INTEGER,
    "count_2xx_3d" INTEGER,
    "count_2xx_15d" INTEGER,
    "count_2xx_30d" INTEGER,
    "count_2xx_all_time" INTEGER,
    "count_3xx_1h" INTEGER,
    "count_3xx_6h" INTEGER,
    "count_3xx_24h" INTEGER,
    "count_3xx_3d" INTEGER,
    "count_3xx_15d" INTEGER,
    "count_3xx_30d" INTEGER,
    "count_3xx_all_time" INTEGER,
    "count_4xx_1h" INTEGER,
    "count_4xx_6h" INTEGER,
    "count_4xx_24h" INTEGER,
    "count_4xx_3d" INTEGER,
    "count_4xx_15d" INTEGER,
    "count_4xx_30d" INTEGER,
    "count_4xx_all_time" INTEGER,
    "count_5xx_1h" INTEGER,
    "count_5xx_6h" INTEGER,
    "count_5xx_24h" INTEGER,
    "count_5xx_3d" INTEGER,
    "count_5xx_15d" INTEGER,
    "count_5xx_30d" INTEGER,
    "count_5xx_all_time" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ResourceOriginMetrics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ResourceMetrics" (
    "id" TEXT NOT NULL,
    "resourceId" TEXT NOT NULL,
    "totalCount1h" INTEGER,
    "totalCount6h" INTEGER,
    "totalCount24h" INTEGER,
    "totalCount3d" INTEGER,
    "totalCount7d" INTEGER,
    "totalCount15d" INTEGER,
    "totalCount30d" INTEGER,
    "totalCountAllTime" INTEGER,
    "uptime1hPct" DOUBLE PRECISION,
    "uptime6hPct" DOUBLE PRECISION,
    "uptime24hPct" DOUBLE PRECISION,
    "uptime3dPct" DOUBLE PRECISION,
    "uptime7dPct" DOUBLE PRECISION,
    "uptime15dPct" DOUBLE PRECISION,
    "uptime30dPct" DOUBLE PRECISION,
    "uptimeAllTimePct" DOUBLE PRECISION,
    "p50_1hMs" INTEGER,
    "p50_6hMs" INTEGER,
    "p50_24hMs" INTEGER,
    "p50_3dMs" INTEGER,
    "p50_7dMs" INTEGER,
    "p50_15dMs" INTEGER,
    "p50_30dMs" INTEGER,
    "p50AllTimeMs" INTEGER,
    "p90_1hMs" INTEGER,
    "p90_6hMs" INTEGER,
    "p90_24hMs" INTEGER,
    "p90_3dMs" INTEGER,
    "p90_7dMs" INTEGER,
    "p90_15dMs" INTEGER,
    "p90_30dMs" INTEGER,
    "p90AllTimeMs" INTEGER,
    "p99_1hMs" INTEGER,
    "p99_6hMs" INTEGER,
    "p99_24hMs" INTEGER,
    "p99_3dMs" INTEGER,
    "p99_7dMs" INTEGER,
    "p99_15dMs" INTEGER,
    "p99_30dMs" INTEGER,
    "p99AllTimeMs" INTEGER,
    "count_2xx_1h" INTEGER,
    "count_2xx_6h" INTEGER,
    "count_2xx_24h" INTEGER,
    "count_2xx_3d" INTEGER,
    "count_2xx_15d" INTEGER,
    "count_2xx_30d" INTEGER,
    "count_2xx_all_time" INTEGER,
    "count_3xx_1h" INTEGER,
    "count_3xx_6h" INTEGER,
    "count_3xx_24h" INTEGER,
    "count_3xx_3d" INTEGER,
    "count_3xx_15d" INTEGER,
    "count_3xx_30d" INTEGER,
    "count_3xx_all_time" INTEGER,
    "count_4xx_1h" INTEGER,
    "count_4xx_6h" INTEGER,
    "count_4xx_24h" INTEGER,
    "count_4xx_3d" INTEGER,
    "count_4xx_15d" INTEGER,
    "count_4xx_30d" INTEGER,
    "count_4xx_all_time" INTEGER,
    "count_5xx_1h" INTEGER,
    "count_5xx_6h" INTEGER,
    "count_5xx_24h" INTEGER,
    "count_5xx_3d" INTEGER,
    "count_5xx_15d" INTEGER,
    "count_5xx_30d" INTEGER,
    "count_5xx_all_time" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ResourceMetrics_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ResourceOriginMetrics_originId_idx" ON "ResourceOriginMetrics"("originId");

-- CreateIndex
CREATE INDEX "ResourceOriginMetrics_originId_createdAt_idx" ON "ResourceOriginMetrics"("originId", "createdAt");

-- CreateIndex
CREATE INDEX "ResourceMetrics_resourceId_idx" ON "ResourceMetrics"("resourceId");

-- CreateIndex
CREATE INDEX "ResourceMetrics_resourceId_createdAt_idx" ON "ResourceMetrics"("resourceId", "createdAt");

-- AddForeignKey
ALTER TABLE "ResourceOriginMetrics" ADD CONSTRAINT "ResourceOriginMetrics_originId_fkey" FOREIGN KEY ("originId") REFERENCES "ResourceOrigin"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ResourceMetrics" ADD CONSTRAINT "ResourceMetrics_resourceId_fkey" FOREIGN KEY ("resourceId") REFERENCES "Resources"("id") ON DELETE CASCADE ON UPDATE CASCADE;
