name: Checks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  foundation:
    name: Foundation
    permissions:
      contents: read
      id-token: write
      packages: read
    uses: Merit-Systems/foundation/.github/workflows/checks.yml@v1
    secrets: inherit
